package byteBuf

type IByteBuf interface {
	Replace(bytes []byte)
	Clear()
	Size() int
	GetBytes() []byte
	CopyRemainData() []byte
	EnsureWrite(remain int)
	ReadBool() (bool, error)
	WriteBool(x bool)
	ReadByte() (byte, error)
	WriteByte(x byte)
	ReadShort() (int16, error)
	WriteShort(x int16)
	ReadFshort() (int16, error)
	WriteFshort(x int16)
	ReadInt() (int32, error)
	WriteInt(x int32)
	ReadUint() (uint32, error)
	WriteUint(x uint32)
	ReadFint() (int32, error)
	WriteFint(x int32)
	ReadLong() (int64, error)
	WriteLong(x int64)
	ReadUlong() (uint64, error)
	WriteUlong(x uint64)
	ReadFlong() (int64, error)
	WriteFlong(x int64)
	ReadFloat() (float32, error)
	WriteFloat(x float32)
	ReadDouble() (float64, error)
	WriteDouble(x float64)
	ReadSint() (int32, error)
	WriteSint(x int32)
	ReadSlong() (int64, error)
	WriteSlong(x int64)
	ReadString() (string, error)
	ReadBytes() ([]byte, error)
	WriteBytes(x []byte)
}
